### ISSUE TITLE
Got error when open fleetmanager plugin

### ISSUE THREAD

**Issue by longzhihun** [spayne/FleetManagerPlugin#2]
`FleetManagerPlugin: Error: The BOTO3 Path c:/Users/seand/AppData/Local/Programs/Python/Python310/lib/site-packages is invalid. Ensure you have installed BOTO3 and have updated project settings See https://github.com/spayne/GameLiftStarterPlugin#step-5---modify-your-project-to-support-gamelift`

I think there is a hardcode somewhere.

**Comment by spayne** [comment]
Check the project settings for the plugin.  You can change that to point to
where your boto3 is installed.

Step 5.2 in the readme.md has a picture and suggests using 'pip show boto3'
to get a path that will work for you.

Hope this helps.
